version: "3"

services:
  node:
    build: .
    container_name: books_api
    tty: true
    stdin_open: true
    command: bash
    env_file: ./.env
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - 3001:3001
    environment:
      PGUSER: postgres
      PGPASSWORD: $POSTGRES_PASSWORD
      PGHOST: $POSTGRES_HOST
      PGDATABASE: railway
      PGPORT: 6954
      PORT: 3001
    networks:
      - books_api_net

  db:
    container_name: books_api_db
    image: postgres
    platform: linux/x86_64
    env_file: ./.env
    restart: always
    ports:
      - 6954:6954
      - 33060:33060
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    networks:
      - books_api_net

networks:
  books_api_net:
    driver: bridge
